version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  cache_server_1:
    build:
      context: .
    container_name: cache_server_1
    ports:
      - "9527:9527"
    environment:
      - PORT=9527
    depends_on:
      - redis
    command: python3 /app/cache_server.py 9527

  cache_server_2:
    build:
      context: .
    container_name: cache_server_2
    ports:
      - "9528:9528"
    environment:
      - PORT=9528
    depends_on:
      - redis
    command: python3 /app/cache_server.py 9528

  cache_server_3:
    build:
      context: .
    container_name: cache_server_3
    ports:
      - "9529:9529"
    environment:
      - PORT=9529
    depends_on:
      - redis
    command: python3 /app/cache_server.py 9529
